trainer:
  gpus: 1
  precision: 16
  min_epochs: 5
  max_epochs: 100
  benchmark: True
  log_every_n_steps: 10
experiment:
  task: "dfc2022"
  module:
    loss: "focaldice"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    in_channels: 4
    num_classes: 16
    ignore_zeros: True  # classes 0 & 15 are not used in scoring
datamodule:
    root_dir: "data/"
    batch_size: 4
    num_workers: 4
    val_split_pct: 0.1
    patch_size: 512
    predict_on: "val"
